// Assignment 3/match-three-app/src/features/game/HighScores.tsx
import React from 'react'
import { useSelector } from 'react-redux'
import { State } from '../../app/store'

export const HighScores = () => {
    const userId = useSelector((state: State) => state.userState.user?.id)
    const game = useSelector((state: State) => state.gameState.game)
    const previousGames = useSelector((state: State) => state.gameState.previousGames)

    return (
        game ? null : (
            <div style={{overflow: 'auto', display: 'flex', flexDirection: 'row', flexWrap: 'wrap' }}>
                <div>
                    <h1> High Scores </h1>
                    <div style={{ width: 500, overflow: 'auto', display: 'flex', flexDirection: 'column', flexWrap: 'wrap' }}>
                        {
                            previousGames?.filter((game) => game.completed && game.user !== userId)
                                .sort((a, b) => b.score - a.score).slice(0, 10)
                                .map((game) => (
                                    <div key={game.id}
                                        style={{
                                            width: 300, height: 100, backgroundColor: 'white',
                                            margin: 3, borderRadius: 5, padding: 10
                                        }}>
                                        <p> User: {game.user} </p>
                                        <p> Score: {game.score} </p>
                                    </div>
                                ))
                        }
                    </div>
                </div>
                <div>
                    <h1> My Best Scores </h1>
                    <div style={{ width: 500, overflow: 'auto', display: 'flex', flexDirection: 'column', flexWrap: 'wrap' }}>
                        {
                            previousGames?.filter((game) => game.completed && game.user === userId)
                                .sort((a, b) => b.score - a.score).slice(0, 3)
                                .map((game) => (
                                    <div key={game.id}
                                        style={{
                                            width: 300, height: 100, backgroundColor: 'white',
                                            margin: 3, borderRadius: 5, padding: 10
                                        }}>
                                        <p> User: {game.user} </p>
                                        <p> Score: {game.score} </p>
                                    </div>
                                ))
                        }
                    </div>
                </div>
            </div>)
    )
}

// Assignment 4/match-three-vue/src/components/HighScores.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import router from '@/router'
import { store } from '../data/store'
import { getGames } from '../data/client'
import type { Game } from '../models/game'

const highScores = ref<Game[]>([])
const personalBest = ref<Game[]>([])
onMounted(async () => {
    if (store.loggedOut()) {
        router.push('/')
    }

    const games = await getGames(store.token)
    highScores.value = games.filter((game) => game.completed && game.user !== store.user?.id).sort((a, b) => b.score - a.score).slice(0, 10)
    personalBest.value = games.filter((game) => game.completed && game.user === store.user?.id).sort((a, b) => b.score - a.score).slice(0, 3)
})

</script>

<template>
    <div style="display: flex; flex-direction: row; justify-content: space-between;">
        <div>
            <h1>High Scores</h1>
            <ol>
                <li v-for="game in highScores" :key="game.id">
                    <div> User: {{ game.user }} </div>
                    <div> Score: {{ game.score }} </div>
                    <div> Moves: {{ game.moves }} </div>
                </li>
            </ol>
        </div>
        <div>
            <h1>Personal Best</h1>
            <ol>
                <li v-for="game in personalBest" :key="game.id">
                    <div> User: {{ game.user }} </div>
                    <div> Score: {{ game.score }} </div>
                    <div> Moves: {{ game.moves }} </div>
                </li>
            </ol>
        </div>
    </div>
</template>
